// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdwJIh95kiNN2AuOazaviZtigxjGqo8-I',
    appId: '1:407130960719:web:260a2d0ad2f73f3bf30b3a',
    messagingSenderId: '407130960719',
    projectId: 'cw06-2e026',
    authDomain: 'cw06-2e026.firebaseapp.com',
    storageBucket: 'cw06-2e026.firebasestorage.app',
    measurementId: 'G-8G5302V90J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfhZWRP8FAUMif7CkzxVZKl9eZnR308BM',
    appId: '1:407130960719:android:90bd5308059764e1f30b3a',
    messagingSenderId: '407130960719',
    projectId: 'cw06-2e026',
    storageBucket: 'cw06-2e026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDst0oDvyk7wWEQn2fp3TKI1gL6cShV_0g',
    appId: '1:407130960719:ios:0cc5d2ce68fc1974f30b3a',
    messagingSenderId: '407130960719',
    projectId: 'cw06-2e026',
    storageBucket: 'cw06-2e026.firebasestorage.app',
    iosBundleId: 'com.example.cw06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDst0oDvyk7wWEQn2fp3TKI1gL6cShV_0g',
    appId: '1:407130960719:ios:0cc5d2ce68fc1974f30b3a',
    messagingSenderId: '407130960719',
    projectId: 'cw06-2e026',
    storageBucket: 'cw06-2e026.firebasestorage.app',
    iosBundleId: 'com.example.cw06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdwJIh95kiNN2AuOazaviZtigxjGqo8-I',
    appId: '1:407130960719:web:990235ab275d0cf9f30b3a',
    messagingSenderId: '407130960719',
    projectId: 'cw06-2e026',
    authDomain: 'cw06-2e026.firebaseapp.com',
    storageBucket: 'cw06-2e026.firebasestorage.app',
    measurementId: 'G-Z5WCY6JSXR',
  );
}
